[QOL-8104] stop robots from indexing resource download URLs
qld-gov-au/opswx-ckan-cookbook pull request #203
Opened 2021-06-17 06:10 UTC by ThrawnCA

- These will often be presigned S3 URLs, which are temporary and so shouldn't be indexed.
Even if they're not, the actual file download isn't the best option to index;
the resource page is the appropriate landing point.

2021-06-18 00:27 UTC, duttonw requested changes
Please also add to robots.txt a block on the s3 bucket's also

Disallow: /<%= node['datashades']['attachments_bucket'] %>/

per 
https://docs.squiz.net/funnelback/knowledgebase/latest/kb-articles/controlling-what-is-indexed.html#robots-meta-tags
which does not support this nice header tag.

hopefully with these two things, the nice url is indexed but the 302 is not.

2021-06-18 05:06 UTC, ThrawnCA commented
> Disallow: /<%= node['datashades']['attachments_bucket'] %>/

Tricky. The `robots.txt` file is in the theme, not in the cookbook, so we don't have access to the exact bucket name. We'd have to just use a "good enough" pattern that will match our current bucket names.

2021-06-21 22:52 UTC, ThrawnCA commented
`robots.txt` is updated in the two theme pull requests.

2021-06-21 23:10 UTC, duttonw approved these changes

2021-06-21 23:48 UTC, merged